"""Compatibility wrapper around Python's stdlib `types` plus Nodus types."""

from types import (
    AsyncGeneratorType,
    BuiltinFunctionType,
    BuiltinMethodType,
    CellType,
    ClassMethodDescriptorType,
    CodeType,
    CoroutineType,
    DynamicClassAttribute,
    EllipsisType,
    FrameType,
    GeneratorType,
    GenericAlias,
    GetSetDescriptorType,
    LambdaType,
    MappingProxyType,
    MemberDescriptorType,
    MethodDescriptorType,
    MethodType,
    MethodWrapperType,
    ModuleType,
    NoneType,
    NotImplementedType,
    SimpleNamespace,
    TracebackType,
    UnionType,
    WrapperDescriptorType,
    coroutine,
    new_class,
    prepare_class,
    resolve_bases,
)

from nodus.frontend.type_system import ANY, BOOL, FLOAT, FUNCTION, INT, LIST, NIL, RECORD, STRING, FunctionType, NodusType

__all__ = [
    # stdlib types (FunctionType omitted — Nodus FunctionType below takes precedence)
    "AsyncGeneratorType",
    "BuiltinFunctionType",
    "BuiltinMethodType",
    "CellType",
    "ClassMethodDescriptorType",
    "CodeType",
    "CoroutineType",
    "DynamicClassAttribute",
    "EllipsisType",
    "FrameType",
    "GeneratorType",
    "GenericAlias",
    "GetSetDescriptorType",
    "LambdaType",
    "MappingProxyType",
    "MemberDescriptorType",
    "MethodDescriptorType",
    "MethodType",
    "MethodWrapperType",
    "ModuleType",
    "NoneType",
    "NotImplementedType",
    "SimpleNamespace",
    "TracebackType",
    "UnionType",
    "WrapperDescriptorType",
    "coroutine",
    "new_class",
    "prepare_class",
    "resolve_bases",
    # Nodus types
    "NodusType",
    "FunctionType",
    "ANY",
    "INT",
    "FLOAT",
    "STRING",
    "BOOL",
    "LIST",
    "RECORD",
    "FUNCTION",
    "NIL",
]
