"""An installed nodus-lang can hand an agent the index (#605).

Nothing in an install used to lead anywhere: the wheel shipped Python and
`stdlib/*.nd`, while `llms.txt`, `docs/` and `skills/` were repo-only, no CLI
command mentioned them, and PyPI strips the README's relative links entirely —
the live page rendered `llms.txt` and `nodus.skill` as plain text with no href.
An agent inside a venv, which is where this was reported from, had no next step.

`llms.txt` now ships as package data. Because `package-data` paths are relative
to the package directory, that requires a *copy* at `src/nodus/llms.txt` — two
files holding one thing, which is the shape this repo spends most of its time
fixing. So the copy is generated by `tools/sync_llms_txt.py` and this test fails
the moment the two differ.
"""

import pathlib
import subprocess
import sys
import unittest

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(REPO))

from nodus.cli import docs as docs_cmd  # noqa: E402
from nodus.support.version import __version__  # noqa: E402

SOURCE = REPO / "llms.txt"
SHIPPED = REPO / "src" / "nodus" / "llms.txt"


# closes: #605
class TheShippedIndexMatchesTheSourceTests(unittest.TestCase):

    def test_the_packaged_copy_exists(self):
        self.assertTrue(
            SHIPPED.is_file(),
            "src/nodus/llms.txt is missing, so the wheel ships no index and "
            "`nodus docs` cannot hand an agent one from inside a venv (#605). "
            "Run `python -m tools.sync_llms_txt`.",
        )

    def test_the_packaged_copy_is_byte_identical(self):
        self.assertEqual(
            SOURCE.read_text(encoding="utf-8"),
            SHIPPED.read_text(encoding="utf-8"),
            "llms.txt and its packaged copy have diverged. The repo-root file is "
            "the source of truth — it is what GitHub serves and what nodus_gate "
            "scans. Run `python -m tools.sync_llms_txt`; do not edit "
            "src/nodus/llms.txt by hand.",
        )

    def test_pyproject_actually_ships_it(self):
        """A copy nobody packages is worse than none: it drifts and helps nobody."""
        pyproject = (REPO / "pyproject.toml").read_text(encoding="utf-8")
        self.assertIn("llms.txt", pyproject,
                      "package-data does not include llms.txt, so it will not "
                      "reach an install")

    def test_the_sync_tool_is_idempotent(self):
        """It must be safe to run when already in step, or nobody will run it."""
        result = subprocess.run(
            [sys.executable, "-m", "tools.sync_llms_txt"],
            cwd=str(REPO), capture_output=True, text=True, timeout=60,
        )
        self.assertEqual(0, result.returncode, result.stderr)
        self.assertIn("already in step", result.stdout)


class NodusDocsPointsSomewhereRealTests(unittest.TestCase):

    def test_the_bundled_index_is_found_from_the_package(self):
        """Resolved relative to the package, not the repo — this is the half that
        has to work inside a venv, where there is no repo."""
        self.assertIsNotNone(docs_cmd.bundled_llms_txt())

    def test_every_entry_names_a_real_place(self):
        for entry in docs_cmd.report()["entries"]:
            with self.subTest(entry=entry["name"]):
                where = entry["where"]
                if entry["local"]:
                    self.assertTrue(pathlib.Path(where).is_file())
                else:
                    # A web link, so check the repo path it is built from exists
                    # rather than making a network call in the suite.
                    suffix = where.split(f"/blob/v{__version__}/", 1)[-1]
                    self.assertTrue(
                        (REPO / suffix.split("#")[0]).exists(),
                        f"{entry['name']} points at {suffix}, which is not in the repo",
                    )

    def test_the_links_are_pinned_to_this_version_not_main(self):
        """An agent on 5.2.0 reading `main`'s guide is how the shipped skill came
        to teach a `timeout_ms` default that had been removed two releases
        earlier."""
        for entry in docs_cmd.report()["entries"]:
            if entry["local"]:
                continue
            with self.subTest(entry=entry["name"]):
                self.assertIn(f"/blob/v{__version__}/", entry["where"])
                self.assertNotIn("/blob/main/", entry["where"])

    def test_the_embedding_entry_mentions_the_breaking_default(self):
        """The one thing an embedder most needs to be told, and the thing the
        stale skill omitted."""
        entries = {e["name"]: e for e in docs_cmd.report()["entries"]}
        self.assertIn("deny by default", entries["Embedding"]["what"])


class TheReadmeSurvivesPypiTests(unittest.TestCase):
    """PyPI renders the README as the project page and **strips relative links**.

    Verified against the live page before this fix: `llms.txt`, `nodus.skill` and
    `project-CLAUDE.md` appeared as text with no href at all. Since
    `readme = "README.md"` and a release's long description is immutable, a
    relative link here is permanent.
    """

    def test_no_relative_links_remain(self):
        import re

        text = (REPO / "README.md").read_text(encoding="utf-8")
        relative = [
            target for target in re.findall(r"\]\(([^)]+)\)", text)
            if not target.startswith(("http://", "https://", "#", "mailto:"))
        ]
        self.assertEqual(
            [], relative,
            "relative link(s) in README.md. PyPI strips these entirely, so they "
            "reach nobody who installed the package — and the page cannot be "
            "fixed after the tag (#605).",
        )

    def test_the_agent_material_is_linked_at_all(self):
        text = (REPO / "README.md").read_text(encoding="utf-8")
        for needle in ("llms.txt", "nodus.skill", "project-CLAUDE.md"):
            with self.subTest(target=needle):
                self.assertIn(needle, text)


if __name__ == "__main__":
    unittest.main()
