"""`nodus test-examples` has examples to run from an installed wheel.

The command shipped, could not work, and said so while returning success. From a
venv it resolved `<venv>/Lib/examples`, printed nine "Missing examples" lines,
and exited **0** — because `_run_examples` failed on a *failing* example and
never on an absent one.

The same hole hid a real gap in the repo: `examples/file_utils_demo.nd` was
pruned on **2026-05-25** and stayed in the command's list. CI runs
`python nodus.py test-examples` as its "Example suite" step, so for **thirty
tagged releases** that step announced a missing example on stderr and passed.

Three things are therefore checked here, and the third is the one that matters:

* the packaged copy exists and is in step with `examples/` (the copy is
  generated by `tools/sync_examples.py`, never hand-edited);
* every file the command names exists in both copies;
* **a missing example is a failure.** Without that, shipping the files fixes
  today's symptom and the next deletion is silent again.

`src/nodus/examples/` is deliberately a subset — only what the command runs and
what those files import. Benchmarks, the orchestration and webhook demos and the
compiler experiment stay repo-only; a wheel is not a place for material nobody
executes from it.
"""

import pathlib
import unittest

from tools import sync_examples

REPO = pathlib.Path(__file__).resolve().parents[1]
SOURCE = REPO / "examples"
SHIPPED = REPO / "src" / "nodus" / "examples"


class ThePackagedCopyIsInStepTests(unittest.TestCase):
    def test_the_packaged_directory_exists(self):
        self.assertTrue(
            SHIPPED.is_dir(),
            "src/nodus/examples/ is missing, so the wheel ships no examples and "
            "`nodus test-examples` cannot run from a venv. "
            "Run `python -m tools.sync_examples`.",
        )

    def test_every_packaged_file_is_byte_identical(self):
        for name in sync_examples.PACKAGED:
            with self.subTest(example=name):
                src, dst = SOURCE / name, SHIPPED / name
                self.assertTrue(dst.is_file(), f"{name} not packaged; run sync_examples")
                self.assertEqual(
                    src.read_text(encoding="utf-8"),
                    dst.read_text(encoding="utf-8"),
                    f"examples/{name} and its packaged copy have diverged. The "
                    f"repo copy is the source of truth; run "
                    f"`python -m tools.sync_examples` and do not edit "
                    f"src/nodus/examples/ by hand.",
                )

    def test_the_package_ships_nothing_the_repo_does_not_have(self):
        """A stale packaged file is a wheel shipping something that was deleted."""
        keep = {(SHIPPED / n).resolve() for n in sync_examples.PACKAGED}
        extra = [
            p.relative_to(SHIPPED).as_posix()
            for p in SHIPPED.rglob("*")
            # `.nodus/` is the bytecode cache running the examples writes beside
            # them. Gitignored, and package-data globs only `*.nd`, so it cannot
            # reach the wheel -- verified by inspecting the built artifact.
            if p.is_file() and ".nodus" not in p.parts and p.resolve() not in keep
        ]
        self.assertEqual(extra, [], "run `python -m tools.sync_examples`")

    def test_pyproject_actually_ships_them(self):
        """A copy nobody packages is worse than none: it drifts and helps nobody."""
        text = (REPO / "pyproject.toml").read_text(encoding="utf-8")
        self.assertIn("examples/*.nd", text)
        self.assertIn("examples/*/*.nd", text)
        self.assertIn("examples/*/*/*.nd", text)


class TheCommandsManifestIsRealTests(unittest.TestCase):
    """`file_utils_demo.nd` was listed for thirty releases after being deleted."""

    def _named(self) -> list[pathlib.Path]:
        from nodus.cli.cli import EXAMPLE_FILES

        return [
            SOURCE.joinpath(*n) if isinstance(n, tuple) else SOURCE / n
            for n in EXAMPLE_FILES
        ]

    def test_every_example_the_command_names_exists(self):
        missing = [str(p.relative_to(REPO)) for p in self._named() if not p.is_file()]
        self.assertEqual(
            missing,
            [],
            "EXAMPLE_FILES names a file that is not in examples/. That is exactly "
            "how file_utils_demo.nd survived its own deletion.",
        )

    def test_every_example_the_command_names_is_packaged(self):
        from nodus.cli.cli import EXAMPLE_FILES

        packaged = {n.replace("\\", "/") for n in sync_examples.PACKAGED}
        for name in EXAMPLE_FILES:
            rel = "/".join(name) if isinstance(name, tuple) else name
            with self.subTest(example=rel):
                self.assertIn(
                    rel,
                    packaged,
                    f"{rel} is run by the command but not shipped, so it would be "
                    f"'missing' from an installed wheel",
                )


class AMissingExampleIsAFailureTests(unittest.TestCase):
    """The half that keeps the rest honest.

    Shipping the files fixes today's symptom. Without this, the next example
    deleted without updating the manifest is silent again — which is the state
    that lasted thirty releases.
    """

    def test_run_examples_returns_nonzero_when_one_is_absent(self):
        import contextlib
        import io

        from nodus.cli import cli as cli_module

        original = cli_module._example_paths
        cli_module._example_paths = lambda: [str(SOURCE / "does-not-exist.nd")]
        try:
            with contextlib.redirect_stderr(io.StringIO()) as err:
                code = cli_module._run_examples()
        finally:
            cli_module._example_paths = original
        self.assertEqual(code, 1, "a missing example must fail the command")
        self.assertIn("Missing examples", err.getvalue())

    def test_run_examples_returns_zero_for_the_real_set(self):
        """The control. Without it the case above passes for a broken command."""
        import contextlib
        import io

        from nodus.cli import cli as cli_module

        with contextlib.redirect_stdout(io.StringIO()):
            with contextlib.redirect_stderr(io.StringIO()):
                code = cli_module._run_examples()
        self.assertEqual(code, 0)


if __name__ == "__main__":
    unittest.main()
