"""Builtin registry definitions."""

from dataclasses import dataclass


@dataclass
class BuiltinInfo:
    name: str
    arity: int | tuple[int, ...]
    fn: object


BUILTIN_NAMES = {
    "clock",
    "type",
    "runtime_typeof",
    "runtime_fn_name",
    "runtime_fn_arity",
    "runtime_fn_module",
    "runtime_fields",
    "runtime_has",
    "runtime_module_fields",
    "runtime_stack_depth",
    "runtime_stack_frame",
    "runtime_tasks",
    "runtime_task",
    "runtime_scheduler_stats",
    "runtime_time",
    "runtime_events",
    "runtime_clear_events",
    "runtime_event_count",
    "coroutine",
    "resume",
    "coroutine_status",
    "spawn",
    "run_loop",
    "sleep",
    "__sleep",
    "channel",
    "send",
    "recv",
    "close",
    "task",
    "graph",
    "run_graph",
    "plan_graph",
    "resume_graph",
    "run_workflow",
    "plan_workflow",
    "resume_workflow",
    "run_goal",
    "plan_goal",
    "resume_goal",
    "workflow_state",
    "workflow_checkpoints",
    "current_workflow_id",
    "emit",
    "tool_call",
    "tool_available",
    "tool_describe",
    "memory_get",
    "memory_put",
    "memory_delete",
    "memory_keys",
    "memory_has",
    "agent_call",
    "agent_available",
    "agent_describe",
    "__action_tool",
    "__action_agent",
    "__action_memory_put",
    "__action_memory_get",
    "__action_emit",
    "str",
    "len",
    "collection_len",
    "count",
    "index_of",
    "last_index_of",
    "range",
    "str_upper",
    "str_lower",
    "str_trim",
    "str_split",
    "str_contains",
    "str_replace",
    "has_key",
    "map_has_key",
    "print",
    "input",
    "keys",
    "values",
    "list_push",
    "list_pop",
    "json_parse",
    "json_stringify",
    "json_parse_int",
    "math_abs",
    "math_min",
    "math_max",
    "math_floor",
    "math_ceil",
    "math_round",
    "math_sqrt",
    "math_random",
    "math_parse_int",
    "math_to_int",
    "math_to_float",
    "math_is_int",
    "math_idiv",
    "math_log",
    "math_pow",
    "math_is_nan",
    "math_is_inf",
    "math_is_finite",
    "math_nan",
    "math_infinity",
    "math_neg_infinity",
    "read_file",
    "write_file",
    "exists",
    "path_exists",
    "append_file",
    "mkdir",
    "list_dir",
    "path_join",
    "path_dirname",
    "path_basename",
    "path_ext",
    "path_stem",
    "fs_mkdir",
    "fs_delete",
    "path_relative",
    "path_absolute",
    "env_get",
    "env_set",
    "env_unset",
    "env_has",
    "env_list",
    "env_list_keys",
    "time_now",
    "time_now_in",
    "time_from_epoch_ms",
    "time_at",
    "time_from_iso8601",
    "time_from_http_date",
    "time_parse",
    "time_ms",
    "time_seconds",
    "time_minutes",
    "time_hours",
    "time_days",
    "time_weeks",
    "time_duration_between",
    "time_add",
    "time_subtract",
    "time_add_days",
    "time_add_months",
    "time_add_years",
    "time_start_of_day",
    "time_end_of_day",
    "time_start_of_week",
    "time_start_of_month",
    "time_start_of_year",
    "time_to_zone",
    "time_to_utc",
    "time_format",
    "time_to_iso8601",
    "time_to_http_date",
    "time_to_epoch_ms",
    "hash_sha256", "hash_sha256_builder", "hash_sha256_file",
    "hash_sha512", "hash_sha512_builder", "hash_sha512_file",
    "hash_blake2b", "hash_blake2b_builder", "hash_blake2b_file",
    "hash_sha1", "hash_sha1_builder", "hash_sha1_file",
    "hash_md5", "hash_md5_builder", "hash_md5_file",
    "hash_hmac_sha256", "hash_hmac_sha512", "hash_hmac_blake2b",
    "hash_hmac_sha1", "hash_hmac_md5",
    "hash_compare",
    "encoding_base64_encode", "encoding_base64_decode",
    "encoding_base64_url_encode", "encoding_base64_url_decode",
    "encoding_hex_encode", "encoding_hex_encode_upper", "encoding_hex_decode",
    "encoding_url_encode", "encoding_url_decode",
    "encoding_url_encode_form", "encoding_url_decode_form",
    "secrets_random_bytes", "secrets_random_int",
    "secrets_token_hex", "secrets_token_base64",
    "secrets_token_urlsafe", "secrets_token_alphanumeric",
    "secrets_uuid_v4", "secrets_uuid_v7",
    "http_get", "http_post", "http_put", "http_delete",
    "http_patch", "http_head", "http_options_verb", "http_request",
    "http_get_async", "http_post_async", "http_put_async", "http_delete_async",
    "http_patch_async", "http_head_async", "http_options_async", "http_request_async",
    "http_stream", "http_sse",
    "subprocess_run", "subprocess_run_async",
    "subprocess_shell", "subprocess_shell_async",
    "subprocess_spawn", "subprocess_spawn_shell",
    "subprocess_shell_quote",
    "tool_register", "tool_unregister", "tool_invoke",
    "tool_lookup", "tool_list", "tool_has",
}



