"""Builtin registry definitions."""

from dataclasses import dataclass
from typing import Any, Callable


@dataclass
class BuiltinInfo:
    name: str
    arity: int | tuple[int, ...]
    fn: Callable[..., Any]


# Marks a call site the *compiler* emitted, which must reach the builtin rather
# than whatever the program happens to have bound to that name (#411).
#
# `CALL` resolves user functions before builtins, so an annotation lowering that
# emits an ordinary `Call(Var("effect_resolve"), …)` hands the program the ability
# to supply the machinery injected into its own code:
#
#     fn effect_resolve(aid) { return {done: true, cached: {result: "FORGED"}} }
#
#     @exactly_once
#     fn work() { return "real" }     // body never runs; work() == "FORGED"
#
# A lowering prefixes the callee with this, and `VM._op_call` strips it and
# dispatches straight to the builtin table — before the user-function lookup.
# The prefix is reserved: the compiler rejects any program that defines a name
# beginning with it, so the namespace cannot be entered from source at all.
#
# This is the general fix, not one per annotation: any future lowering meant to
# hold *against the program's author* — capability checks, declared-effect
# enforcement, dependency guards — gets it by using `Compiler.builtin_call()`.
BUILTIN_CALL_PREFIX = "__nodus_builtin__"


BUILTIN_NAMES = {
    "clock",
    "type",
    "runtime_typeof",
    "runtime_fn_name",
    "runtime_fn_arity",
    "runtime_fn_module",
    "runtime_fields",
    "runtime_has",
    "runtime_module_fields",
    "runtime_stack_depth",
    "runtime_stack_frame",
    "runtime_tasks",
    "runtime_task",
    "runtime_capabilities",
    "runtime_scheduler_stats",
    "runtime_time",
    "runtime_events",
    "runtime_clear_events",
    "runtime_event_count",
    "coroutine",
    "resume",
    "coroutine_status",
    "spawn",
    # #395/#157: the two task verbs. Registered in builtins/coroutine.py;
    # this set is what the compiler resolves against, so a builtin missing here
    # compiles as an ordinary name and fails in a way that names nothing.
    "cancel",
    "wait",
    "run_loop",
    "sleep",
    "__sleep",
    "channel",
    "send",
    "recv",
    "close",
    "task",
    "graph",
    "run_graph",
    "plan_graph",
    "resume_graph",
    "run_workflow",
    "plan_workflow",
    "resume_workflow",
    "run_goal",
    "plan_goal",
    "resume_goal",
    "workflow_state",
    "workflow_arg",
    "workflow_resume_payload",
    "workflow_wait",
    "workflow_checkpoints",
    "current_workflow_id",
    "emit",
    "tool_call",
    "tool_available",
    "tool_describe",
    "memory_get",
    "memory_put",
    "memory_delete",
    "memory_keys",
    "memory_has",
    "agent_call",
    # #616: the async twin was in the VM dispatch table and not here, so it
    # was outside `register_function`'s override guard *and* outside the
    # capability classification -- a policy denying `agent.call` refused
    # `agent_call` and allowed `agent_call_async` against the same agent.
    "agent_call_async",
    "agent_available",
    "agent_describe",
    "__workflow_checkpoint",
    "__action_tool",
    "__action_agent",
    "__action_memory_put",
    "__action_memory_get",
    "__action_emit",
    "str",
    "len",
    "collection_len",
    "count",
    "index_of",
    "last_index_of",
    "range",
    "str_upper",
    "str_lower",
    "str_trim",
    "str_split",
    "str_contains",
    "str_startswith",
    "str_endswith",
    "str_replace",
    "has_key",
    "map_has_key",
    "print",
    "input",
    "keys",
    "values",
    "list_push",
    "push",
    "list_pop",
    "json_parse",
    "json_stringify",
    "json_parse_int",
    "math_abs",
    "math_min",
    "math_max",
    "math_floor",
    "math_ceil",
    "math_round",
    "math_sqrt",
    "math_random",
    "math_parse_int",
    "math_to_int",
    "math_to_float",
    "math_is_int", "math_is_float", "math_is_numeric",
    "type_eq", "bool_equal",
    "math_idiv",
    "math_log",
    "math_pow",
    "math_is_nan",
    "math_is_inf",
    "math_is_finite",
    "math_nan",
    "math_infinity",
    "math_neg_infinity",
    "math_bit_and",
    "math_bit_or",
    "math_bit_xor",
    "math_bit_not",
    "math_bit_lshift",
    "math_bit_rshift",
    "read_file",
    "read_file_bytes",
    "write_file",
    "write_file_bytes",
    "exists",
    "path_exists",
    "append_file",
    "mkdir",
    "list_dir",
    "path_join",
    "path_dirname",
    "path_basename",
    "path_ext",
    "path_stem",
    "fs_mkdir",
    "fs_delete",
    "path_relative",
    "path_absolute",
    "env_get",
    "env_set",
    "env_unset",
    "env_has",
    "env_list",
    "env_list_keys",
    "time_now",
    "time_now_in",
    "time_from_epoch_ms",
    "time_at",
    "time_from_iso8601",
    "time_from_http_date",
    "time_parse",
    "time_ms",
    "time_seconds",
    "time_minutes",
    "time_hours",
    "time_days",
    "time_weeks",
    "time_duration_between",
    "time_add",
    "time_subtract",
    "time_add_days",
    "time_add_months",
    "time_add_years",
    "time_start_of_day",
    "time_end_of_day",
    "time_start_of_week",
    "time_start_of_month",
    "time_start_of_year",
    "time_to_zone",
    "time_to_utc",
    "time_format",
    "time_to_iso8601",
    "time_to_http_date",
    "time_to_epoch_ms",
    "hash_sha256", "hash_sha256_builder", "hash_sha256_file",
    "hash_sha512", "hash_sha512_builder", "hash_sha512_file",
    "hash_blake2b", "hash_blake2b_builder", "hash_blake2b_file",
    "hash_sha1", "hash_sha1_builder", "hash_sha1_file",
    "hash_md5", "hash_md5_builder", "hash_md5_file",
    "hash_hmac_sha256", "hash_hmac_sha512", "hash_hmac_blake2b",
    "hash_hmac_sha1", "hash_hmac_md5",
    "hash_compare",
    "encoding_base64_encode", "encoding_base64_decode",
    "encoding_base64_url_encode", "encoding_base64_url_decode",
    "encoding_hex_encode", "encoding_hex_encode_upper", "encoding_hex_decode",
    "encoding_url_encode", "encoding_url_decode",
    "encoding_url_encode_form", "encoding_url_decode_form",
    "secrets_random_bytes", "secrets_random_int",
    "secrets_token_hex", "secrets_token_base64",
    "secrets_token_urlsafe", "secrets_token_alphanumeric",
    "secrets_uuid_v4", "secrets_uuid_v7",
    "http_get", "http_post", "http_put", "http_delete",
    "http_patch", "http_head", "http_options_verb", "http_request",
    "http_get_async", "http_post_async", "http_put_async", "http_delete_async",
    "http_patch_async", "http_head_async", "http_options_async", "http_request_async",
    "http_stream", "http_sse",
    "subprocess_run", "subprocess_run_async",
    "subprocess_shell", "subprocess_shell_async",
    "subprocess_spawn", "subprocess_spawn_shell",
    "subprocess_shell_quote",
    "tool_register", "tool_unregister", "tool_invoke",
    "tool_lookup", "tool_list", "tool_has",
    "test_assert", "test_assert_eq", "test_assert_neq",
    "test_assert_err", "test_assert_ok", "test_assert_kind",
    "test_assert_throws", "test_assert_close",
    "test_assert_contains", "test_assert_has_key", "test_assert_in_range",
    "test_suite", "test_case", "test_case_async", "test_skip",
    "test_before_all", "test_after_all", "test_before_each", "test_after_each",
    "test_fixture", "test_cleanup",
    "test_parameterize",
    "test_advance_clock", "test_flush_async",
    "runtime_trace_id", "runtime_session_id", "runtime_execution_unit_id",
    "memory_recall_from", "memory_recall_all", "memory_share",
    "syscall", "syscall_list",
    "effect_resolve", "effect_pending", "effect_complete", "effect_action_id", "effect_store_size",
    "effect_get_result",
    "state_contribute",
    "chr", "ord",
    "collection_validate_reduce_fn",
    "retry_available", "retry_call",
    "cb_available", "cb_create", "cb_call", "cb_state", "cb_reset",
}




